function [Codex_File,SS] = readCodex3_Trevor(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  S21000V1500RPM6P2K232115 = IMPORTFILE1(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a
%  string array.
%
%  S21000V1500RPM6P2K232115 = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  S21000V1500RPM6p2k232115 = importfile1("\\mmrc.hboi.edu\jerlov$\Raw Data\2024\202408XX_LUMEX03\CODEX\20240903_S2_1000V_1500RPM_6p2k_232115.csv", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 22-Nov-2024 10:57:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 41);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Timestamp23211541209032024UTC", "AverageCount200", "AverageRate10", "SampleRate40000", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Timestamp23211541209032024UTC", "AverageCount200", "AverageRate10", "SampleRate40000", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Timestamp23211541209032024UTC", "AverageCount200", "AverageRate10", "SampleRate40000", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41"], "EmptyFieldRule", "auto");

% Import the data
Codex_File = readmatrix(filename, opts);
SS = size(Codex_File);

end