poolobj = gcp("nocreate");
delete(poolobj);
pool = parpool("Processes");
options = trainingOptions("sgdm", ...
MaxEpochs=15, ...
ValidationData=imdsValidation, ...
ValidationFrequency=15, ...
Plots="training-progress", ...
Metrics="accuracy", ...
ExecutionEnvironment="parallel-cpu",...
Verbose=false);
net = trainnet(imdsTrain,net_1,"crossentropy",options);
scores = predict(net,imdsTest);
classList = (repmat([1,2,3,4,5,6],309,1))';
labels = classList(max(scores) == scores);
% classNames = categories(imds.Labels);
YValidation = imdsTest.Labels;
% YTest = scores2label(scores,classNames);
YTest = categorical(labels);
accuracy = mean(YValidation == YTest)
plotconfusion(YTest,imdsTest.Labels)
